language: go

go:
  - 1.6
  - 1.7
  - release
  - tip

install:
  - go get -t -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover

script:
  - go test -coverprofile=renderer.coverprofile
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race .

matrix:
  allow_failures:
    - go: tip
